[client]

#toolbarMode = "minimal"
showSidebarNavigation = false

[server]
headless = true

runOnSave = true

[browser]

gatherUsageStats = false
[ui]
#hideTopBar = true

[theme]

base = "dark"
primaryColor = "red"
